students = []
students.append('David')
students.append('953')
print("students[] = ", students)
print("max(students) = ", max(students))
print("min(students) = ", min(students))
print("students[slice(2)] = ", students[slice(2)])
students.append('Aung')
students.append('Ye Htet')
students.append('StudentA')
students.append('Person2')
print("students[] = ", students)
print("max(students) = ", max(students))
print("min(students) = ", min(students))
print("students[slice(2)] = ", students[slice(2)])